### ISSUE TITLE
Replit issue

### ISSUE THREAD

**Issue by blackxfiied** [holy-unblocker/website-aio#27]
This is what is shows whenever I leave this idle with a replit:

{
	"versions": [
		"v1",
		"v2"
	],
	"language": "NodeJS",
	"memoryUsage": 5.44,
	"project": {
		"name": "bare-server-node",
		"description": "TOMPHTTP NodeJS Bare Server",
		"repository": "https://github.com/tomphttp/bare-server-node",
		"version": "1.1.0"
	}
}

that's all the webpage returns.

**Comment by MasterCubo** [comment]
I second this, and I want to add the Shell message when running `npm install`. 
```
~/website-aio$ npm install
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

added 437 packages, and audited 438 packages in 2m

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.19.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.2
npm notice Run npm install -g npm@8.19.2 to update!
npm notice 
Detected change in environment, reloading shell...
```

Maybe the deprecated packages are creating non-fatal errors within the code?

**Comment by MasterCubo** [comment]
I would like to add, for @e9x’s sake, that this is solely a Replit issue. My heroku deployment worked perfectly as planned. This could either be how heroku installs its packages during pre/deployment, or how it runs the packages. I know in my experience, replit can be very picky about being isolated running files and installing packages, at least in Python and Java. Projects that aren’t in verified package repos like PyPI generally have lots of issues installing and getting referenced correctly. Alternatively, heroku does everything behind the scenes, at least from what I’ve seen in the past day, and I’m not sure if it individually installs the required packages or simply uses `npm install`. I could be wrong, but heroku could work because it installs packages BEFORE running npm install. I could be completely incorrect as I am an extreme noob to Node.js. Just my 2 cents ✌️

**Comment by e9x** [comment]
@MasterCubo Heroku doesn't do too much behind the scenes. I can explain the flow that it does:

1. Copy contents of website-aio repository to a disposable Debian image
2. Install dependencies (with dev dependencies for the next step! `--include=dev`)
3. Try to build the project: `npm run build`
4. If this fails or the build script doesn't exist, Heroku moves on
5. Copy the build artifacts (compiled code, cache) to a production server
6. Install only non-dev dependencies on the production server with `npm install` (`--omit=dev`)
7. `npm start`

**Comment by e9x** [comment]
Holy Unblocker uses a traditional workflow for scripts. We install the projects we clone or install and use `pm2` to run them in the background. On my end it is the same. Surely I would have found this issue if it were reproducible on a more "normal" Linux system..

**Comment by e9x** [comment]
I will have to investigate this on replit. I notice the original issue is the Bare server metadata is shown after being left idle..

**Comment by e9x** [comment]
Haven't investigated this and I also don't think it's important. This issue seems very unlikely.

**Comment by TotoB12** [comment]
I have it to
